//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string bookId { get; set; }
        public string pNr { get; set; }
        public string empId { get; set; }
        public string bookedDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
