//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string category { get; set; }
        public string year { get; set; }
        public string isbn { get; set; }

        public Book()
        {

        }

        public Book(string title, string author, string category, string year, string isbn)
        {
            this.title = title;
            this.author = author;
            this.category = category;
            this.year = year;
            this.isbn = isbn;

        }
    }
}
